In [20]:
import numpy as np
from sympy.matrices import *

In [1]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [6]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
data = sm.datasets.get_rdataset("dietox", "geepack").data
md = smf.mixedlm("Weight ~ Time", data, groups=data["Pig"])
mdf = md.fit()
print(mdf.summary())

         Mixed Linear Model Regression Results
Model:            MixedLM Dependent Variable: Weight    
No. Observations: 861     Method:             REML      
No. Groups:       72      Scale:              11.3669   
Min. group size:  11      Likelihood:         -2404.7753
Max. group size:  12      Converged:          Yes       
Mean group size:  12.0                                  
--------------------------------------------------------
             Coef.  Std.Err.    z    P>|z| [0.025 0.975]
--------------------------------------------------------
Intercept    15.724    0.788  19.952 0.000 14.179 17.268
Time          6.943    0.033 207.939 0.000  6.877  7.008
groups RE    40.394    2.149                            



In [16]:
import numpy as np
from statsmodels.datasets import grunfeld
data = grunfeld.load_pandas().data
data.year = data.year.astype(np.int64)
# MultiIndex, entity - time
data = data.set_index(['firm','year'])
from linearmodels import PanelOLS
mod = PanelOLS(data.invest, data[['value','capital']], entity_effects=True)
res = mod.fit(cov_type='clustered', cluster_entity=True)

/home/sara/myenv/lib64/python3.6/site-packages/linearmodels/panel/model.py:1164: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  params = np.linalg.lstsq(x, y)[0]
/home/sara/myenv/lib64/python3.6/site-packages/linearmodels/panel/model.py:1220: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  wy -= root_w * np.linalg.lstsq(root_w, wy)[0]
/home/sara/myenv/lib64/python3.6/site-packages/linearmodels/panel/model.py:1221: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M 

In [2]:
iris = load_iris()
X, y = iris.data, iris.target
X.shape

(150, 4)

In [3]:
X_new = SelectKBest(chi2, k=2).fit_transform(X, y)
X_new.shape

(150, 2)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
w = np.matrix(([0,2,3],[4,0,6],[7,8,0]))
# Dot product
np.dot(w, np.linalg.inv(w))
# Transpose of a matrix
w.T
# (Multiplicative) Inverse of a matrix (better!)
np.linalg.inv(w)
#  (Moore-Penrose) Pseudo-Inverse of a matrix
np.linalg.pinv(w)

matrix([[-0.26666667,  0.13333333,  0.06666667],
        [ 0.23333333, -0.11666667,  0.06666667],
        [ 0.17777778,  0.07777778, -0.04444444]])

In [50]:
T = 3
I = 3
r = .0

identity_I = np.identity(I)
identity_I_1 = np.identity(I-1)
neg1 = np.negative(np.ones((1, I-1)))
# Not-squared matrix
Q = np.append(identity_I_1, neg1, axis=0)

In [51]:
Q

array([[ 1.,  0.],
       [ 0.,  1.],
       [-1., -1.]])

In [52]:
identity_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
for i in range(3):
    w[i] = w[i]/w[i].sum()

In [54]:
w

matrix([[0.        , 0.375     , 0.625     ],
        [0.35294118, 0.        , 0.64705882],
        [0.44303797, 0.55696203, 0.        ]])

In [55]:
(Q.dot(np.linalg.inv(identity_I - r*w))).dot((np.linalg.inv(identity_I - r*w.T)).dot(Q.T))

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [47]:
(np.linalg.inv(identity_I - r*w.T)).dot(Q.T)

matrix([[ 1.,  0.],
        [ 0.,  1.],
        [-1., -1.]])

In [45]:
Q.dot(Q.T)

array([[2., 1.],
       [1., 2.]])

In [ ]:
L = Q.dot(np.linalg.inv(I-r*w)).dot(np.linalg.inv(I-r*w.T)).dot(Q.T)
L

In [5]:
L.shape

(2, 2)

In [5]:
w.T.dot(w)

array([[1.46716294, 1.23101532, 1.28753804],
       [1.23101532, 1.11235845, 1.09311417],
       [1.28753804, 1.09311417, 1.26146965]])

In [6]:
a = w.T
a.dot(w)

array([[1.46716294, 1.23101532, 1.28753804],
       [1.23101532, 1.11235845, 1.09311417],
       [1.28753804, 1.09311417, 1.26146965]])

In [15]:
Q.dot(np.linalg.inv(I-r*w)).dot(np.linalg.inv(I-r*w).T).dot(Q.T)

array([[2040.96323856, 2241.16242678],
       [2241.16242678, 2527.08179582]])

In [16]:
np.linalg.det(L)

134872.02287082712

In [8]:
import pandas as pd
df = pd.DataFrame({'a':['a','b','c'], 'b':np.arange(3)})
df

a  b
0  a  0
1  b  1
2  c  2

In [9]:
df[df.columns] = np.roll(df, shift=-1, axis=0)
df

a  b
0  b  1
1  c  2
2  a  0

In [10]:
df = pd.DataFrame({'a':['a','b','c']})
df

a
0  a
1  b
2  c

In [11]:
df.reindex([1,2,0])

a
1  b
2  c
0  a

In [ ]:
# initialization of ro
ro = np.random.rand()

# Var definition
I = len(regions_cap)
T = len(years)
W = temp_W

identity_I = np.identity(I)
identity_I_1 = np.identity(I-1)
neg1 = np.negative(np.ones((I-1, 1)))
# Not-squared matrix
Q = np.append(identity_I_1, neg1, axis=1)