In [20]:
import numpy as np
from sympy.matrices import *

In [25]:
w = np.matrix(([0,2,3],[4,0,6],[7,8,0]))
# Dot product
np.dot(w, np.linalg.inv(w))
# Transpose of a matrix
w.T
# (Multiplicative) Inverse of a matrix (better!)
np.linalg.inv(w)
#  (Moore-Penrose) Pseudo-Inverse of a matrix
np.linalg.pinv(w)

matrix([[-0.26666667,  0.13333333,  0.06666667],
        [ 0.23333333, -0.11666667,  0.06666667],
        [ 0.17777778,  0.07777778, -0.04444444]])

In [50]:
T = 3
I = 3
r = .0

identity_I = np.identity(I)
identity_I_1 = np.identity(I-1)
neg1 = np.negative(np.ones((1, I-1)))
# Not-squared matrix
Q = np.append(identity_I_1, neg1, axis=0)

In [51]:
Q

array([[ 1.,  0.],
       [ 0.,  1.],
       [-1., -1.]])

In [52]:
identity_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
for i in range(3):
    w[i] = w[i]/w[i].sum()

In [54]:
w

matrix([[0.        , 0.375     , 0.625     ],
        [0.35294118, 0.        , 0.64705882],
        [0.44303797, 0.55696203, 0.        ]])

In [55]:
(Q.dot(np.linalg.inv(identity_I - r*w))).dot((np.linalg.inv(identity_I - r*w.T)).dot(Q.T))

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [47]:
(np.linalg.inv(identity_I - r*w.T)).dot(Q.T)

matrix([[ 1.,  0.],
        [ 0.,  1.],
        [-1., -1.]])

In [45]:
Q.dot(Q.T)

array([[2., 1.],
       [1., 2.]])

In [ ]:
L = Q.dot(np.linalg.inv(I-r*w)).dot(np.linalg.inv(I-r*w.T)).dot(Q.T)
L

In [5]:
L.shape

(2, 2)

In [5]:
w.T.dot(w)

array([[1.46716294, 1.23101532, 1.28753804],
       [1.23101532, 1.11235845, 1.09311417],
       [1.28753804, 1.09311417, 1.26146965]])

In [6]:
a = w.T
a.dot(w)

array([[1.46716294, 1.23101532, 1.28753804],
       [1.23101532, 1.11235845, 1.09311417],
       [1.28753804, 1.09311417, 1.26146965]])

In [15]:
Q.dot(np.linalg.inv(I-r*w)).dot(np.linalg.inv(I-r*w).T).dot(Q.T)

array([[2040.96323856, 2241.16242678],
       [2241.16242678, 2527.08179582]])

In [16]:
np.linalg.det(L)

134872.02287082712

In [8]:
import pandas as pd
df = pd.DataFrame({'a':['a','b','c'], 'b':np.arange(3)})
df

a  b
0  a  0
1  b  1
2  c  2

In [9]:
df[df.columns] = np.roll(df, shift=-1, axis=0)
df

a  b
0  b  1
1  c  2
2  a  0

In [10]:
df = pd.DataFrame({'a':['a','b','c']})
df

a
0  a
1  b
2  c

In [11]:
df.reindex([1,2,0])

a
1  b
2  c
0  a

In [ ]:
# initialization of ro
ro = np.random.rand()

# Var definition
I = len(regions_cap)
T = len(years)
W = temp_W

identity_I = np.identity(I)
identity_I_1 = np.identity(I-1)
neg1 = np.negative(np.ones((I-1, 1)))
# Not-squared matrix
Q = np.append(identity_I_1, neg1, axis=1)